import { RpdDataModel } from "~/types";

export default {
  maintainedBy: "cronJob",
  namespace: "sys",
  name: "sys_cron_job",
  singularCode: "sys_cron_job",
  pluralCode: "sys_cron_jobs",
  schema: "public",
  tableName: "sys_cron_jobs",
  properties: [
    {
      name: "id",
      code: "id",
      columnName: "id",
      type: "integer",
      required: true,
      autoIncrement: true,
    },
    {
      name: "code",
      code: "code",
      columnName: "code",
      type: "text",
      required: true,
    },
    {
      name: "description",
      code: "description",
      columnName: "description",
      type: "text",
      required: false,
    },
    {
      name: "cronTime",
      code: "cronTime",
      columnName: "cron_time",
      type: "text",
      required: true,
    },
    {
      name: "disabled",
      code: "disabled",
      columnName: "disabled",
      type: "boolean",
      required: true,
      defaultValue: "false",
    },
    {
      name: "jobOptions",
      code: "jobOptions",
      columnName: "job_options",
      type: "json",
      required: false,
    },
    {
      name: "isRunning",
      code: "isRunning",
      columnName: "is_running",
      type: "boolean",
      required: true,
      defaultValue: "false",
    },
    {
      name: "nextRunningTime",
      code: "nextRunningTime",
      columnName: "next_running_time",
      type: "datetime",
      required: false,
    },
    {
      name: "lastRunningTime",
      code: "lastRunningTime",
      columnName: "last_running_time",
      type: "datetime",
      required: false,
    },
    // success, failed, error
    {
      name: "lastRunningResult",
      code: "lastRunningResult",
      columnName: "last_running_result",
      type: "text",
      required: false,
    },
    {
      name: "lastError",
      code: "lastError",
      columnName: "last_error",
      type: "text",
      required: false,
    },
    {
      name: "actionHandlerCode",
      code: "actionHandlerCode",
      columnName: "action_handler_code",
      type: "text",
      required: false,
    },
    {
      name: "handler",
      code: "handler",
      columnName: "handler",
      type: "text",
      required: false,
    },
    {
      name: "handleOptions",
      code: "handleOptions",
      columnName: "handle_options",
      type: "json",
      required: false,
    },
    {
      name: "onError",
      code: "onError",
      columnName: "on_error",
      type: "text",
      required: false,
    },
  ],
} as RpdDataModel;
